reformatted todo

diff --git a/scripts/grimblast b/scripts/grimblast
--- a/scripts/grimblast
+++ b/scripts/grimblast
@@ -142,14 +142,11 @@ notifyOpen() {
   if [ "$OPENFILE_NOTIFICATION" = "no" ]; then
     notifyOk "$@"
   else
-    outt=$(notifyOk -A "default=open_folder" "$@")
+    outt=$(notifyOk -A "default=Open with Sushi" "$@")
     if [ "$outt" == "default" ]; then
-      # this does not work for filenames with commas in them
-      if dbus-send --session --print-reply --dest=org.freedesktop.FileManager1 --type=method_call /org/freedesktop/FileManager1 org.freedesktop.FileManager1.ShowItems array:string:"file://$4" string:""; then
-        :
-      else
-        notify-send -t 3000 -a grimblast "Error displaying folder with dbus-send"
-        echo "Displayed: Error displaying folder with dbus-send"
+      if ! sushi "$4"; then
+        notify-send -t 3000 -a grimblast "Error opening with sushi"
+        echo "Error opening with sushi"
       fi
     fi
   fi
@@ -314,7 +311,7 @@ elif [ "$ACTION" = "edit" ]; then
 else
   if [ "$ACTION" = "copysave" ]; then
     takeScreenshot - "$GEOM" "$OUTPUT" | tee "$FILE" | wl-copy --type image/png || die "Clipboard error"
-    notifyOk "Screenshot captured!" -i "$FILE"
+    notifyOpen "Screenshot captured!" "" -i "$FILE"
     echo "$FILE"
   else
     notifyError "Error taking screenshot with grim"
